name: "Podcast Generator"
author: "Bruno Janeiro"
description: "Generates a feed for a podcast from YAML file"
runs:
  using: "docker"
  image: "Dockerfile"
branding:
  icon: "git-branch"
  color: "green"
inputs:
  email:
    description: The commiter's e mail address 
    required: true
    default: ${{ github.actor }}@localhost
  name:
    description: The commiter's name
    required: true
    default: ${{ github.actor }}